### ISSUE TITLE
Failed save to disk/removable drive on Linux (Mint 19)

### ISSUE THREAD

**Issue by rburema** [fieldOfView/Cura-ArcWelderPlugin#22]
When testing the recent new submission on Linux Mint 19, on saving a sliced gcode file that had arc welding enabled, it shows an error message, and also has an error in the logs. Here's my full log: [cura.log](https://github.com/fieldOfView/Cura-ArcWelderPlugin/files/6814064/cura.log)

The relevant bit is this:
~~~
2021-07-14 08:34:20,556 - DEBUG - [MainThread] RemovableDriveOutputDevice.RemovableDriveOutputDevice.requestWrite [85]: Writing to /media/remco/VERBATIM/UMS3_Door_Stop_2.ufp
2021-07-14 08:34:20,568 - DEBUG - [MainThread] ArcWelderPlugin.ArcWelderPlugin._filterGcode [241]: Using temporary file /tmp/tmpu_ro_mc4
2021-07-14 08:34:20,571 - DEBUG - [MainThread] ArcWelderPlugin.ArcWelderPlugin._filterGcode [266]: Running ArcWelder with the following options: ['/home/remco/.local/share/cura/4.10/plugins/ArcWelderPlugin/ArcWelderPlugin/bin/linux/ArcWelder', '-m=1000000.000000', '-t=0.050000', '-r=0.050000', '-s=1.000000', '-a=12', '-g', '/tmp/tmpu_ro_mc4']
2021-07-14 08:34:20,575 - ERROR - [MainThread] UM.Logger.logException [112]: Exception: Unable to write to file UMS3_Door_Stop_2: module 'subprocess' has no attribute 'STARTUPINFO'
2021-07-14 08:34:20,577 - ERROR - [MainThread] UM.Logger.logException [116]: Traceback (most recent call last):
2021-07-14 08:34:20,579 - ERROR - [MainThread] UM.Logger.logException [116]:   File "/home/ultimaker/src/output/build/inst/lib/python3.8/site-packages/UM/Qt/Bindings/OutputDeviceManagerProxy.py", line 150, in _writeToDevice
2021-07-14 08:34:20,582 - ERROR - [MainThread] UM.Logger.logException [116]:   File "/tmp/.mount_UltimaKlG5xS/usr/bin/plugins/plugins/RemovableDriveOutputDevice/RemovableDriveOutputDevice.py", line 99, in requestWrite
2021-07-14 08:34:20,584 - ERROR - [MainThread] UM.Logger.logException [116]:     self.writeStarted.emit(self)
2021-07-14 08:34:20,586 - ERROR - [MainThread] UM.Logger.logException [116]:   File "/home/ultimaker/src/output/build/inst/lib/python3.8/site-packages/UM/Signal.py", line 219, in emit
2021-07-14 08:34:20,588 - ERROR - [MainThread] UM.Logger.logException [116]:   File "/home/ultimaker/src/output/build/inst/lib/python3.8/site-packages/UM/Signal.py", line 336, in __performEmit
2021-07-14 08:34:20,590 - ERROR - [MainThread] UM.Logger.logException [116]:   File "/home/ultimaker/src/output/build/inst/lib/python3.8/site-packages/UM/Signal.py", line 219, in emit
2021-07-14 08:34:20,592 - ERROR - [MainThread] UM.Logger.logException [116]:   File "/home/ultimaker/src/output/build/inst/lib/python3.8/site-packages/UM/Signal.py", line 332, in __performEmit
2021-07-14 08:34:20,594 - ERROR - [MainThread] UM.Logger.logException [116]:   File "/home/remco/.local/share/cura/4.10/plugins/ArcWelderPlugin/ArcWelderPlugin/ArcWelderPlugin.py", line 272, in _filterGcode
2021-07-14 08:34:20,596 - ERROR - [MainThread] UM.Logger.logException [116]:     startupinfo = subprocess.STARTUPINFO()
2021-07-14 08:34:20,598 - ERROR - [MainThread] UM.Logger.logException [116]: AttributeError: module 'subprocess' has no attribute 'STARTUPINFO'
~~~

**Comment by rburema** [comment]
I can confirm that this fix works at least.
